name: auto-merger
on:
  status: {}
  pull_request:
    types: [labeled, synchronize, opened, edited, reopened, unlocked]
    
jobs:
  merge-on-green:
    runs-on: ubuntu-latest
    steps:
      - name: merge-on-green
        uses: "pascalgn/automerge-action@81b1d6dc0637009760e051c80fb4d060d495aa7d"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"  
          MERGE_LABELS: "merge-on-green" 
          MERGE_METHOD:  "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: 20
          MERGE_RETRY_SLEEP:  60000
          
