name: merge-on-green
on:
  status:
jobs:
  merge-on-green:
    runs-on: ubuntu-latest
    steps:
      - name: merge-on-green
        uses: "pascalgn/automerge-action@733fcc62d711705eae9cd66fcf49c93c1d1a98c6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"  
          MERGE_LABELS: "merge-on-green" 
          MERGE_METHOD:  "squash"
