name: tests

on: push

jobs:
  example-workflow:
    name: Example workflow using the Check CRLF action
    runs-on: ubuntu-latest

    steps:
      - name: Sleep
        uses: maddox/actions/sleep@master
        with:
          args: 15
